Picture
msu-anthropology/indian-country-ss20 pull request #18
Opened 2020-03-19 22:53 UTC by lerouxga

2020-03-19 23:24 UTC, 0Redfeather requested changes
Hello, so the code for your image looks good, but your image is in the wrong place. You put it in sites/js/images when you meant to put it in your project folder at sites/lerouxsmith1/img. Fix this by moving it from the one folder to yours, and submit another pull request then you'll be good!

2020-03-19 23:31 UTC, lerouxga commented
I moved it! On the github website it wont let me create a new pull request it still has my original pull request named picture up!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Zach Francis <notifications@github.com>
Sent: Thursday, March 19, 2020 7:24:46 PM
To: msu-anthropology/indian-country-ss20 <indian-country-ss20@noreply.github.com>
Cc: Leroux, Bella <lerouxga@msu.edu>; Author <author@noreply.github.com>
Subject: Re: [msu-anthropology/indian-country-ss20] Picture (#18)


@0Redfeather requested changes on this pull request.

Hello, so the code for your image looks good, but your image is in the wrong place. You put it in sites/js/images when you meant to put it in your project folder at sites/lerouxsmith1/img. Fix this by moving it from the one folder to yours, and submit another pull request then you'll be good!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/msu-anthropology/indian-country-ss20/pull/18*pullrequestreview-378159027__;Iw!!HXCxUKc!ndR9dQ6Jnfe4qQ2REE0JS0PncPvkmazjvqEi4OeEETQtWSYl6SCX4fdjxPwmQxE$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AOLQ5QBZM6ACEYSOSJQ6DR3RIKST5ANCNFSM4LPYBNAA__;!!HXCxUKc!ndR9dQ6Jnfe4qQ2REE0JS0PncPvkmazjvqEi4OeEETQtWSYl6SCX4fdj7SNzNbI$>.

2020-03-19 23:35 UTC, 0Redfeather commented
Yup, looks like you did not have to do another pull request. That's nice to know on my end! All your code looks good though, good job. We'll approve it by next Monday once everybody turns their stuff in. Take care.

2020-03-22 21:50 UTC, 0Redfeather approved these changes

2020-03-23 00:25 UTC, merged